[versions]
java = "21"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
springCloudVersion = "2025.0.0"
lombok = "1.18.42"

[libraries]
# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-test-junit5
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm
kotlinx-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-test
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

[plugins]
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.multiplatform
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.spring
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
# https://plugins.gradle.org/plugin/org.springframework.boot
springBoot = { id = "org.springframework.boot", version = "4.0.2" }
# https://plugins.gradle.org/plugin/io.spring.dependency-management
springDependecyManager = { id = 'io.spring.dependency-management', version = '1.1.7' }
